[build]
  base = "frontend"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://13.201.10.69:8000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
