[build]
  base = "frontend"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://wmsa-alb-1972898098.ap-south-1.elb.amazonaws.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
