'use client'

import { useState } from 'react'
import { FileDown, FileText, Code2, Loader2, Download } from 'lucide-react'
import { useToast } from './Toast'
import { useAppSelector } from '../store'
import { API_BASE } from '../services/api'

interface ReportSummaryProps {
  onSelectSeverity?: (sev: string) => void
  targetUrl?: string
}

const RISK_TONE: Record<string, string> = {
  None: 'text-slate-600 bg-slate-50 border-slate-200 dark:text-slate-300 dark:bg-slate-900 dark:border-slate-700',
  Low: 'text-emerald-700 bg-emerald-50 border-emerald-200 dark:text-emerald-300 dark:bg-emerald-950/60 dark:border-emerald-800',
  Medium: 'text-amber-700 bg-amber-50 border-amber-200 dark:text-amber-300 dark:bg-amber-950/60 dark:border-amber-800',
  High: 'text-orange-700 bg-orange-50 border-orange-200 dark:text-orange-300 dark:bg-orange-950/60 dark:border-orange-800',
  Critical: 'text-red-700 bg-red-50 border-red-200 dark:text-red-300 dark:bg-red-950/60 dark:border-red-800',
}

export default function ReportSummary({ onSelectSeverity, targetUrl = 'http://127.0.0.1:3000' }: ReportSummaryProps) {
  const { toast } = useToast()
  const summary = useAppSelector((s) => s.summary.data)
  const [downloading, setDownloading] = useState<string | null>(null)

  const sev = summary?.findings.by_severity ?? {}
  const total = summary?.findings.total ?? 0

  // Reports are generated by the backend from stored findings and evidence. There is no client-side fallback.
  const handleDownload = async (format: 'pdf' | 'json' | 'html') => {
    setDownloading(format)
    try {
      const res = await fetch(`${API_BASE}/report/export?format=${format}`)
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 120)}`)
      const blob = format === 'json' ? new Blob([JSON.stringify(await res.json(), null, 2)], { type: 'application/json' }) : await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `worldmonitor_security_report.${format}`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      toast('success', `${format.toUpperCase()} report exported`, `Generated by the backend from ${total} stored finding(s).`)
    } catch (e: any) {
      toast('error', `${format.toUpperCase()} export failed`, e.message || 'Backend unreachable')
    }
    setDownloading(null)
  }

  return (
    <div id="report-summary-section" className="card px-5 py-4 flex flex-wrap items-center justify-between gap-4">
      <div className="flex items-center gap-2">
        <FileText size={16} className="text-teal-600 dark:text-teal-400" />
        <span className="text-xs font-semibold text-slate-800 dark:text-slate-100">Assessment Reports</span>
      </div>

      <div className="flex items-center gap-6 flex-wrap text-xs text-slate-600 dark:text-slate-300">
        <div>
          <span className="text-slate-400 mr-1.5">Application:</span>
          <span className="font-semibold font-mono text-[11px]">{targetUrl.replace(/^https?:\/\//, '').replace(/\/.*$/, '')}</span>
        </div>
        <div title={summary?.risk.formula}>
          <span className="text-slate-400 mr-1.5">Risk:</span>
          <span className={`inline-block px-2 py-0.5 rounded border font-semibold text-[11px] ${RISK_TONE[summary?.risk.level ?? 'None']}`}>
            {summary ? `${summary.risk.level} (${summary.risk.score})` : '--'}
          </span>
        </div>
        {(['CRITICAL', 'HIGH'] as const).map((k) => (
          <button
            key={k}
            onClick={() => onSelectSeverity?.(k[0] + k.slice(1).toLowerCase())}
            className="flex items-center hover:bg-slate-100 dark:hover:bg-slate-800 px-2 py-1 rounded transition-colors cursor-pointer"
          >
            <span className="text-slate-400 mr-1.5">{k[0] + k.slice(1).toLowerCase()}:</span>
            <span className={`font-bold ${k === 'CRITICAL' ? 'text-red-600 dark:text-red-400' : 'text-orange-600 dark:text-orange-400'}`}>{sev[k] ?? 0}</span>
          </button>
        ))}
        <div>
          <span className="text-slate-400 mr-1.5">Total findings:</span>
          <span className="font-bold text-slate-800 dark:text-slate-200">{total}</span>
        </div>
      </div>

      <div className="flex items-center gap-2 flex-wrap">
        <button onClick={() => handleDownload('pdf')} disabled={downloading !== null} className="btn-primary text-xs flex items-center gap-1.5 cursor-pointer disabled:opacity-50 bg-teal-600 hover:bg-teal-700">
          {downloading === 'pdf' ? <Loader2 size={13} className="animate-spin" /> : <FileDown size={13} />}
          Export PDF
        </button>
        <button onClick={() => handleDownload('json')} disabled={downloading !== null} className="btn-secondary text-xs flex items-center gap-1.5 cursor-pointer disabled:opacity-50">
          {downloading === 'json' ? <Loader2 size={13} className="animate-spin" /> : <Download size={13} />}
          Export JSON
        </button>
        <button onClick={() => handleDownload('html')} disabled={downloading !== null} className="btn-secondary text-xs flex items-center gap-1.5 cursor-pointer disabled:opacity-50">
          {downloading === 'html' ? <Loader2 size={13} className="animate-spin" /> : <Code2 size={13} />}
          Export HTML
        </button>
      </div>
    </div>
  )
}
